blog/article/urls.py
from django.conf.urls import url
from article import views

urlpatterns = [
    url(r'^$', views.article, name='article'),
    url(r'^articleCreate/$', views.articleCreate, name='articleCreate'),
    url(r'^articleRead/(?P<articleId>[0-9]+)/$', views.articleRead, name='articleRead'),
    url(r'^articleUpdate/(?P<articleId>[0-9]+)/$', views.articleUpdate, name='articleUpdate'),
    url(r'^articleDelete/(?P<articleId>[0-9]+)/$', views.articleDelete, name='articleDelete'),
    url(r'^articleSearch/$', views.articleSearch, name='articleSearch'),
    url(r'^articleSearchh/$', views.articleSearchh, name='articleSearchh'),
]

blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
     url(r'^admin/', admin.site.urls),
     url(r'^main/', include('main.urls', namespace='main')),
     url(r'^article/', include('article.urls', namespace='article')),
     url(r'^book/', include('book.urls', namespace='book')),     
     url(r'^.*', include('main.urls')),
     ]

blog/book/urls.py
from django.conf.urls import url
from book import views

urlpatterns = [
    url(r'^$', views.book, name='book'),
]

blog/main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [    
    url(r'^$', views.main,name='main'),
    url(r'^about/$', views.about, name='about'),
    url(r'^book/$', views.book, name='book'),   
    ]

blog/article/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField()       
    pubDateTime = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title
    class Meta:
        ordering = ('-pubDateTime', )
    
    
    
class Comment(models.Model):
    article = models.ForeignKey(Article)
    content = models.CharField(max_length=128)
    pubDateTime = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.article.title + '-' + str(self.id)    

blog/book/models.py
from django.db import models

class book(models.Model):
    title = models.CharField(max_length=128, unique=True)
    authors = models.CharField(max_length=128, unique=True)
    publish = models.CharField(max_length=128, unique=True)
    pubDate = models.DateField(auto_now_add=True)
    version = models.IntegerField(default=1)
    price = models.IntegerField()
    
    
    def __str__(self):
        return self.title
    
    
    

blog/main/models.py
from django.db import models

# Create your models here.

blog/article/forms.py
from django import forms
from article.models import Article

class ArticleForm(forms.ModelForm):
    title = forms.CharField(label='標題', max_length=128)
    content = forms.CharField(label='內容', widget=forms.Textarea)
    class Meta:
        model = Article
        fields = ['title', 'content']

blog/article/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db.models.query_utils import Q

from article.models import Article, Comment
from article.forms import ArticleForm

def article(request):
    '''
    Render the article page
    '''
    articles = Article.objects.all()
    itemsList = []
    for article in articles:
        items = [article]
        items.extend(list(Comment.objects.filter(article=article)))
        itemsList.append(items)
    context = {'itemsList':itemsList}
    
    return render(request, 'article/article.html', context)

def articleCreate(request):
    '''
    Create a new article instance
    1. If method is GET, render an empty form
    2 . If method is POST, perform form validation. Display error messages if the form is invalid
    3. Save the form to the model and redirect to the article page
    '''
    template = 'article/articleCreateUpdate.html'
    if request.method == 'GET':
        return render(request, template, {'articleForm':ArticleForm()})
    
    # POST
    articleForm = ArticleForm(request.POST)
    if not articleForm.is_valid():
        return render(request, template, {'articleForm':articleForm})
    articleForm.save()
    messages.success(request, '文章已新增了')
    return redirect('article:article')

def articleRead(request, articleId):
    '''
    Read an article
        1. Get the "article" instance using "articleId"; redirect to the 404 page if not found
        2. Render the articleRead template with article instance and its
            associated comments
    '''
    articleToRead = get_object_or_404(Article, id=articleId)
    context = {
        'article': articleToRead,
        'comments': Comment.objects.filter(article=articleToRead)
    }
    return render(request, 'article/articleRead.html', context)


def articleUpdate(request, articleId):
    '''
    Update the article instance:
        1. Get the article to update; redirect to 404 if not found
        2. Render a bound form if the method is GET
        3. If the form is valid, save it to the model, otherwise render a
           bound form with error messages
    '''
    articleToUpdate = get_object_or_404(Article, id=articleId)
    template = 'article/articleCreateUpdate.html'
    if request.method == 'GET':
        articleForm = ArticleForm(instance=articleToUpdate)
        return render(request, template, {'articleForm':articleForm, 'article':articleToUpdate})
    # POST
    articleForm = ArticleForm(request.POST, instance=articleToUpdate)
    if not articleForm.is_valid():
        return render(request, template, {'articleForm':articleForm, 'article':articleToUpdate})
    articleForm.save()
    messages.success(request, '文章已修改')
    return redirect('article:articleRead', articleId=articleId)


def articleDelete(request, articleId):
    '''
    Delete the article instance:
        1. Render the article page if the method is GET
        2. Get the article to delete; redirect to 404 if not found
    '''
    if request.method == 'GET':
        return article(request)
    # POST
    articleToDelete = get_object_or_404(Article, id=articleId)
    articleToDelete.delete()
    messages.success(request, '文章已刪除')
    return redirect('article:article')


def articleSearch(request):
    '''
    Search for articles:
        1. Get the "searchTerm" from the HTML page
        2. Use "searchTerm" for filtering
    '''
    searchTerm = request.GET.get('searchTerm')
    articles = Article.objects.filter(Q(title__icontains=searchTerm) |
                                      Q(content__icontains=searchTerm))
    context = {'articles':articles, 'searchTerm':searchTerm}
    return render(request, 'article/articleSearch.html', context)
    # Or try this at the last line: return article(request)
    
def articleSearchh(request):
    '''
    Search for articles:
        1. Get the "searchTerm" from the HTML page
        2. Use "searchTerm" for filtering
    '''
    searchTerm = request.GET.get('searchTerm')
    articles = Article.objects.filter()
    context = {'articles':articles, 'searchTerm':searchTerm}
    return render(request, 'article/articleSearch.html', context)
    # Or try this at the last line: return article(request)
    
    
    
    
    

blog/book/views.py
from django.shortcuts import render

# Create your views here.
def book (request):
    '''
    Render the book page
    '''
    return render(request, 'book/book.html')

blog/main/views.py
from django.shortcuts import render
import datetime

def main(request):
    '''
    Render the main pages
    '''
    now = datetime.datetime.now()
    context = {'like':' 我很讚','now':now} 
    return render(request,'main/main.html',context)

def about(request):
    '''
    Render the about pages
    '''
    now = datetime.datetime.now()
    context = {'like':'你很讚','now':now} 
    return render(request,'main/about.html',context)

def book(request):
    '''
    Render the book pages
    '''
    now = datetime.datetime.now()
    context = {'like':'Django 很讚','now':now} 
    return render(request,'main/book.html',context)

blog/article/templates/article/article.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>美食秀</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
<link rel="icon" href="{% static 'main/img/favicon.ico' %} " type="image/x-icon }">
</head>
<body>
{% include 'main/menu.html' %}
{% include 'main/messages.html' %}
<h1>食在好吃歐～</h1>
{% include 'article/searchForm.html' %}
<p class="inlineBlock"><a class="btn" href="{% url 'article:articleCreate' %}">新增美食</a></p>
<br><br><hr>
{% include 'main/messages.html' %}
{% for items in itemsList %}
{% for item in items %}
{% if forloop.first %}
 <h3><a href="{% url 'article:articleRead' item.id %}">{{ item.title }}</a></h3>
 <form class="inlineBlock" method="post" action="{% url 'article:articleDelete' item.id %}">
   {% csrf_token %}
   <input class="btn" type="submit" value="刪除">
</form>
 <div class=articleContent>{{ item.content|linebreaks|truncatechars_html:30 }}</div>
 <p>發表時間：{{ item.pubDateTime|date:'Y-m-d H:i' }}</p>
 <p>讚：{{ item.likes }}</p>
 {% else %}
 <p>
 <span class=comment>{{ item.content }}</span><br>
 <span class=commentTime>{{ item.pubDateTime|date:'m 月 d 日 H:i'}}</span>
 </p>
 {% endif %}
 {% endfor %}
 <hr>
{% endfor %}
</body>
</html>

blog/article/templates/article/articleCreate.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h2>新增文章</h2>
<form method="post" action="{% url 'article:articleCreate' %}">
  {% csrf_token %}
  {{ articleForm.as_p }}
<input type="submit" value="送出">
<a class="btn" href="{% url 'article:article' %}">放棄</a>
</form>
</body>
</html>

blog/article/templates/article/articleCreateUpdate.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>修改文章</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="icon" href="{% static 'main/img/favicon.ico' %} " type="image/x-icon }">
</head>
<body>
{% include 'main/menu.html' %}
{% if article %}
  <h2>修改文章</h2>
  <form method="post" action="{% url 'article:articleUpdate' article.id %}">
{% else %}
  <h2>新增文章</h2>
  <form method="post" action="{% url 'article:articleCreate' %}">
{% endif %}
  {% csrf_token %}
  {{ articleForm.as_p }}
<input class="btn" type="submit" value="送出">
<a class="btn" href="{% url 'article:articleSearchh' %}">放棄</a>
</form>
</body>
</html>

blog/article/templates/article/articleRead.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>{{ article.title }}</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
<link rel="icon" href="{% static 'main/img/favicon.ico' %} " type="image/x-icon }">
</head>
<body>
{% include 'main/menu.html' %}
{% include 'main/messages.html' %}
<p><h3 class="inlineBlock">標題：{{ article.title }}</h3><p/>
{% include 'article/searchForm.html' %}


<p><a class="btn inlineBlock" href="{% url 'article:articleUpdate' article.id %}">修改文章</a></p>

<p>內容介紹：
<div class=articleContent>{{ article.content|linebreaks }}</div>

<p>讚:{{ article.likes }}</p>
<p>發表時間 >>>>{{ article.pubDateTime|date:'Y-m-d H:i' }}</p>
{% for comment in comments %}
  <p>
    <span class=comment>{{ comment.content }}</span><br>
    <span class=commentTime>{{ comment.pubDateTime|date:'Y-m-d H:i'}}</span>
  </p>
{% endfor %}
</body>
</html>

blog/article/templates/article/articleSearch.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>總覽</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="icon" href="{% static 'main/img/favicon.ico' %} " type="image/x-icon }">
</head>
<body>
{% include 'main/menu.html' %}
<h1>美食總覽區 方便您查詢～</h1>
{% include 'article/searchForm.html' %}
<br><br><hr>
{% if not articles %}
  <p>查無資料</p>
{% else %}
  <table class="table table-striped table-hover">
    <tr><th>店名</th><th>發表時間</th>
    {% for article in articles %}
    <tr>
      <td><a href="{% url 'article:articleRead' article.id %}">{{ article.title }}</a></td>
      <td>{{ article.pubDateTime|date:'Y-m-d H:i' }}</td>
    </tr>
    {% endfor %}
  </table>
{% endif %}
</body>
</html>

blog/article/templates/article/articleSearchh.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>總覽</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="icon" href="{% static 'main/img/favicon.ico' %} " type="image/x-icon }">
</head>
<body>
{% include 'main/menu.html' %}
<h1>美食總覽區 方便您查詢～</h1>
{% include 'article/searchForm.html' %} 
<p class="inlineBlock"><a class="btn" href="{% url 'article:articleCreate' %}">新增美食</a></p> 
<br><br><hr>
{% if not articles %}
  <p>查無資料</p>
{% else %}
  <table class="table table-striped table-hover">
    <tr><th>店名</th><th>發表時間</th>
    {% for article in articles %}
    <tr>
      <td><a href="{% url 'article:articleRead' article.id %}">{{ article.title }}</a></td>
      <td>{{ article.pubDateTime|date:'Y-m-d H:i' }}</td>
    </tr>
    {% endfor %}
  </table>
{% endif %}
</body>
</html>

blog/article/templates/article/searchForm.html
<form class="inlineBlock" action="{% url 'article:articleSearch' %}">
  <input type="text" name="searchTerm" {% if searchTerm %}value="{{ searchTerm }}"{% endif %}>
  <input class="btn" type="submit" value="店家查詢">
</form>

blog/book/templates/book/book.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>書籍</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h1>這裡是書籍--Hello world!</h1>
<p>書櫃  book 林怡璇要做什麼網頁</p>
<br>
</body>
</html>

blog/main/templates/main/about.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>地圖</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="icon" href="{% static 'main/img/favicon.ico' %} " type="image/x-icon }">
</head>
</head>
<body>
{% include 'main/menu.html' %}
<h1>看見吉峰東路 </h1>
<p>放 地圖   跟map 連結
</p>


<br>
<p>現在時間：{{ now }}</p>
</body>
</html>

blog/main/templates/main/main.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>首頁</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="icon" href="{% static 'main/img/favicon.ico' %} " type="image/x-icon }">
</head>
<body>
<background src="static 'main/img/maps-1217.gif">
{% include 'main/menu.html' %}
<h1>聽我跟你說 霧峰 !</h1>
<h2><font color="red" >歷史</font></h2>
<hr>
<p>&emsp;&emsp;霧峰舊稱「阿罩霧」，一說為出自平埔族貓羅社所居之地的原住民族阿罩霧社（Ataabu社，或譯阿他霧社）；另說則為此地東半部山區經常煙霧繚繞，因而得名。霧峰最有影響力的氏族屬林家，人稱霧峰林家。與板橋林家（無親屬關係）、鹿港辜家、高雄陳家、基隆顏家並列為近代顯赫的台灣五大家族。</p>
<p>&emsp;&emsp;霧峰地區自古為為平埔洪雅族貓羅社（Bnauro）、Ataabu社與泰雅族賽考列克群的聚居地。明鄭時期隸屬於天興縣，清康熙時期，隸屬於台灣府諸羅縣，雍正初年，為彰化縣貓羅堡轄區範圍，開始有漢人沿大肚溪至溪東開發柳樹湳。乾隆年間，此地始設「貓羅新莊」。而根據伊能嘉矩的考證，自清領時期，就出現霧峰一名，作為阿罩霧的雅稱。</p>
<p>&emsp;&emsp;1887年台灣建省，改隸台灣府台灣縣貓羅堡。1895年日治初期，改為台灣民政支部彰化出張所貓羅堡。隔年，台灣民政支部改為台中縣。1900年，再改制為台中廳貓羅堡。1920年阿罩霧正式改為霧峰，設置霧峰庄，屬台中州大屯郡管轄。</p>
<p>&emsp;&emsp;1945年12月，中華民國政府接收台灣，改制為臺中縣大屯區「霧峰鄉」。1950年撤廢區署，改為臺中縣霧峰鄉。1954年臺灣省政府疏遷至台灣中部地區，包含秘書處、衛生處及教育廳等遷至於此，並設置「光復新村」省府宿舍，1954年秘書處、衛生處遷往南投中興新村。1956年「北溝文物陳列室」開館，為國立故宮博物院舊址。1958年台灣省最高民意機關「臺灣省議會」設立於此。1998年實施精省計畫，台灣省議會改制為「臺灣省諮議會」，多數省府機關改隸屬中央部會或改制為中部辦公室。</p>
<p>&emsp;&emsp;2010年12月25日隨著省轄臺中市與台中縣合併為直轄市，霧峰鄉也改制為臺中市「霧峰區」。</p>

<h2><font color="red" >地理</font></h2>
<hr>
<h3><font color="#0072E3" >地形</font></h3>
<p>&emsp;&emsp;霧峰區，位於台中盆地之東側和台中山地之交界處。盆地和坡地地形，約各佔一半。以車籠埔斷層為界，西側屬台中盆地的一部分，以沖積扇平地為主；東側屬丘陵地形，以東南側為高，等高線多在200-500公尺之間。 全區地勢呈東南高，西北低；其中則以東南山境為最高峰－－「霧峰奧山」，又稱霧峰契山，海拔標高483公尺，位於青桐林生態產業園區內，與大橫屏山山脈並行。
</p>
<h3><font color="#0072E3" >水文</font></h3>
<h4><font color="#F75000" >&emsp;河川</font></h4>
<p>&emsp;&emsp;流經該區河川，主要有大里溪、草湖溪、北溝溪、乾溪、烏溪（依河道相對位置自北至南排列）。均屬烏溪（舊稱大肚溪）水系，主以東側高處向西流。大里溪、草湖溪位於該區北側；烏溪位於該區南側，是該區最大的河川。經濟部水利署中區水資源局及水利規劃試驗所亦位於霧峰。
</p>
<h4><font color="#F75000" >&emsp;水利發展</font></h4>
<p>&emsp;&emsp;早期在漢人入墾時，多以私設埤圳維持農田灌溉，因霧峰水利發達，所以農業豐富。
</p>
<p>&emsp;&emsp;&emsp;*乾隆三十年間（1765年），大墾戶吳洛（墾號「吳伯榮」）修建萬斗六圳，引烏溪灌溉約一千餘甲田園。
<p>&emsp;&emsp;&emsp;*道光十八年（1838年），霧峰林家[[林定邦]]修建『[[阿罩霧圳]]』（今霧峰圳），後因開墾土地面積逐漸擴增，就將其他埤圳，如『番仔圳』、『丁台圳』、『南勢圳』等合併為中型水圳。由於設施的完備，伴著促進商業興盛的土地『[[墾戶制度]]』，移民耕墾勤奮，於是中部米產數量大增，成為當時臺灣最大米倉。
<p>&emsp;&emsp;&emsp;*大正十二年（1923年），日本政府改制，本區屬於『大屯埤圳水利組合』。
<p>&emsp;&emsp;&emsp;*民國三十五年（1946年），改為「農田水利協會」，民國三十七年（1948年），改稱為『水利委員會』，現在的『阿罩霧圳』隸屬於南投[[農田水利會]]，引烏溪水穿鑿象鼻坑後，分第一幹線『車籠埤』，再分「霧峰圳」及「王厝圳」，第二幹線分「番仔圳」、「丁台圳」及「南勢圳」。
</p>
<h2><font color="red" >氣候</font></h2>
<hr>
<p>&emsp;&emsp;霧峰區屬副熱帶季風氣候，年平均溫度19.4℃，氣溫以5月至9月最高，平均氣溫攝氏20度以上，1、2月份平均溫度攝氏約16至17度。 雨量方面，降雨多集中於夏季，佔全年雨量75﹪以上，尤以颱風季節雨量更為驚人，可能單日即達100mm；冬季較為乾旱，因水田面積較廣，常受旱災影響。由於東半部地勢較高，丘陵綿延，所以山區雨量較多，西半部平原地勢較低，降雨較少，平均年雨量在1400mm至1670mm之間，由於本區位於山麓地帶，河川支流眾多而水氣，午過後常有霧氣出現，山峰雲霧圍繞，而有霧峰之名。
<br><br><br><br><br><br><br><br><br>






<h3><font color="#007500" >時間看我啦 >>>> {{ now }}</h3>
</body>
</html>

blog/main/templates/main/menu.html
<marquee behavior=alternate>歡迎光臨本網站</marquee>
<ul id="menu">
  <li><a href="{% url 'main:main' %}">霧峰簡介</a></li>  
  <li><a href="{% url 'main:about' %}">吉峰東路地圖</a></li>
  <li><a href="{% url 'article:article' %}">朝陽山下美食</a></li>
  <li><a href="{% url 'book:book' %}">意見回饋</a></li>    
  
  <form class="inlineBlock" action="{% url 'article:articleSearchh' %}">  
  <input class="btn" type="submit" value="朝楊山下美食">
</form>
  <hr>
</ul>

 

blog/main/templates/main/messages.html
{% for message in messages %}
  <p {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</p>
{% endfor %}